### ISSUE TITLE
Solicitação de ajuda

### ISSUE THREAD

**Issue by Dev-Jago** [allicedimello/allicedimello#1]
Olá alice, rsrsrs estou começando minha jornada na programação agora, através da plataforma dio. Lá eu estava fuçando no perfil do povo no GitHub pra entender melhor como funciona e etc... até q me deparei com o seu perfil e achei muito legal esse seu README, vc tem alguma sujestão de tutorial ou curso em markdown para que eu possa aprender a montar uma introdução assim em para meus portfólios?
desculpa escrever isso como issue kkk é que ainda não sei muito bem usar a plataforma

**Comment by allicedimello** [comment]
Olá, desculpa a demora, só agora vi a sua mensagem
A princípio segui esse tutorial para criar o ReadMe: https://www.alura.com.br/artigos/como-criar-um-readme-para-seu-perfil-github
Depois fui pegando algumas inspirações nesse projeto da DIO, como os utilitários que coloquei no final: https://github.com/digitalinnovationone/dio-lab-open-source
E peguei algumas dicas nesse artigo que tá muito legal também: https://dev.to/reginadiana/como-escrever-um-readme-md-sensacional-no-github-4509

Espero que te ajude, qualquer dúvida estou à disposição ;)

**Comment by Dev-Jago** [comment]
AAA vlw Allice logo estarei aprimorando meu perfil aqui no GitHub, agradece!
